### ISSUE TITLE
What's the proper way to reset the watcher?

### ISSUE THREAD

**Issue by rmvz3** [gurinderhans/SwiftFSWatcher#4]
Hi again.

I've been working with the library and I managed to do what I want but I've noticed the watcher stops monitoring selected folders sometimes. The only way I found to get the library triggering events for the stuck folder again was reseting my app. I've tried to pause/resume the fileWatcher but nothing changes. Is there a proper way to restart the watcher completely?

Thanks

**Comment by gurinderhans** [comment]
Is there a specific reason for the event watcher to stop monitoring some folders? If the issue is easily reproducible then let me know so I can debug it better and maybe fix the underlying issue. Otherwise, if you can somehow detect when monitoring stops, you can try to set your watcher variable to `nil` and reinitialize it with same paths as this will completely reset everything.

**Comment by rmvz3** [comment]
Hi.

In fact, If I make fileWatcher var optional and I set to nil, I always get an EXC_BAD_ACCESS from SwiftFSWatcher’s private method innerEventCallback. However I’ve just done the same thing to the class where the fileWatcher is initialized and it seems to work as expected.

But now I found a even more strange behavior. I keep having events from folders I’ve removed from the array of watching directories!

Even making the aforementioned observer class reset when I remove a folder path the events still are notified. I log the watching folders on fileWatcher and the the deleted paths are really gone but still...

I guess I’m having something wrong (no idea what, tho) but this is something easy to test so I’d like you to confirm I’m crazy. ^_^U

Thanks

-- 
Ricardo Mantero

El 6 de junio de 2016 a las 7:59:04, Gurinder Hans (notifications@github.com) escribió:

Is there a specific reason for the event watcher to stop monitoring some folders? If the issue is easily reproducible then let me know so I can debug it better and maybe fix the underlying issue. Otherwise, if you can somehow detect when monitoring stops, you can try to set your watcher variable to nil and reinitialize it with same paths as this will completely reset everything.

**Comment by gurinderhans** [comment]
`If I make fileWatcher var optional and I set to nil`, you can't do this since the initial watcher has to be `class scoped` and be initialized there as well, so yea you got this part fixed.

**I keep having events from folders I’ve removed from the array of watching directories!**
- I will have a look at this tonight, as it could just be a simple bug where I'm not internally refreshing the watching paths. In the meantime can you try to `pause` then `resume` after the the file / directory is removed from the array to refresh the watcher?

PS: By no means this watcher is perfect, so you're probably not crazy :p

**Comment by rmvz3** [comment]
Yeah, I’ve confirmed it doesn’t change behavior if paths are added or deleted once initialized. I mean, the watchingPaths do change but the events seems to be the same. The pause/resume doesn’t work for me either. Since I’ve built my app based on this library and I love the results I’ve got with it, I’m going to try to restart the app when the paths change (this should be very unfrequent). My app is a menu bar app so I guess it won’t be even noticed. Of course, if you come up with a proper fix I’ll be even more grateful :)

Thank you for your interest.

-- 
Ricardo Mantero

El 6 de junio de 2016 a las 22:01:53, Gurinder Hans (notifications@github.com) escribió:

If I make fileWatcher var optional and I set to nil, you can't do this since the initial watcher has to be class scoped and be initialized there as well, so yea you got this part fixed.

I keep having events from folders I’ve removed from the array of watching directories!

I will have a look at this tonight, as it could just be a simple bug where I'm not internally refreshing the watching paths. In the meantime can you try to pause then resume after the the file / directory is removed from the array to refresh the watcher?
PS: By no means this watcher is perfect, so you're probably not crazy :p

**Comment by gurinderhans** [comment]
I can confirm the behavior you're facing since the `paths` aren't actually being updated in the actual `FSEventStream`, just `watchingPaths` is updated which doesn't do much. I will put out a fix in a day or two :)

**Comment by rmvz3** [comment]
Thak you! :) 

-- 
Ricardo Mantero

El 7 de junio de 2016 a las 7:29:46, Gurinder Hans (notifications@github.com) escribió:

I can confirm the behavior you're facing since the paths aren't actually being updated in the actual FSEventStream, just watchingPaths is updated which serves no purpose. I will put out a fix in a day or two :)
